import { BriefcaseBusiness, Clock3, Earth, MapPinned } from "lucide-react";
import { roles, skillGroups, testimonials } from "@/data/portfolio";

export function Testimonials() { return <section className="section shell testimonials"><div className="section-head"><div><p className="eyebrow">Testimonials</p><h2>Trusted collaboration,<br/>measured delivery.</h2></div><p>Demo testimonials are visible and clearly labelled until verified recommendations are provided.</p></div><div className="testimonial-grid">{testimonials.map(item => <blockquote key={item.name}><span>Demo · replace later</span><p>“{item.quote}”</p><footer><strong>{item.name}</strong><small>{item.role}</small></footer></blockquote>)}</div></section>; }

export function Availability() {
  const items = [{ icon: Earth, title: "Remote worldwide", text: "Available for distributed Flutter and mobile engineering teams." }, { icon: MapPinned, title: "Relocation", text: "Open to Germany, wider Europe and USA opportunities." }, { icon: BriefcaseBusiness, title: "Work setup", text: "Remote, hybrid or on-site roles considered." }, { icon: Clock3, title: "Notice period", text: "Demo: 30 days · replace with confirmed availability." }];
  return <section className="availability-section" id="availability"><div className="shell availability-grid"><div><p className="eyebrow">Availability</p><h2>Open to ambitious<br/>mobile teams worldwide.</h2></div><div className="availability-cards">{items.map(({ icon: Icon, title, text }) => <article key={title}><Icon size={20}/><strong>{title}</strong><p>{text}</p></article>)}</div></div></section>;
}

export function Expertise() { return <section className="expertise" id="expertise"><div className="shell section"><div className="section-head light"><div><p className="eyebrow">Core expertise</p><h2>From architecture<br/>to app-store release.</h2></div><p>Complete mobile delivery: technical decisions, implementation, testing, automation and post-launch health.</p></div><div className="skill-grid">{skillGroups.map((group,index) => <article key={group.title}><span>0{index+1}</span><h3>{group.title}</h3><ul>{group.items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div><div className="capabilities"><div><strong>Real-time & media</strong><p>WebRTC, Agora, ZegoCloud, live streaming, WebSockets and background audio.</p></div><div><strong>Security & performance</strong><p>OAuth 2.0, JWT, SSL pinning, obfuscation, profiling and crash monitoring.</p></div><div><strong>Payments & growth</strong><p>Stripe, RevenueCat, SSLCommerz, subscriptions, release ownership and ASO.</p></div></div></div></section>; }

export function Experience() { return <section className="section shell experience" id="experience"><div className="section-head"><div><p className="eyebrow">Experience</p><h2>A builder with<br/>production ownership.</h2></div><p>Progressing from hands-on implementation to architecture and end-to-end delivery.</p></div><div className="timeline">{roles.map((item,index) => <article key={item.company}><div className="timeline-index">0{index+1}</div><div className="timeline-date">{item.date}</div><div className="timeline-role"><h3>{item.role}</h3><span>{item.company}</span></div><p>{item.text}</p></article>)}</div><div className="education"><span>Education</span><div><strong>BSc in Computer Science & Engineering</strong><p>Uttara University · 2019—2023</p></div><div><strong>Thesis</strong><p>E-commerce platform · React, Spring Boot & PostgreSQL</p></div></div></section>; }
